

Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ACCOUNTING ECONOMICS AND LAW-A CONVIVIUM','Publications')
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ADELAIDE LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ADMINISTRATIVE LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AFRICAN JOURNAL OF INTERNATIONAL AND COMPARATIVE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AIR & SPACE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ALBERTA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ALTERNATIVE LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AMERICAN BANKRUPTCY LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AMERICAN BUSINESS LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AMERICAN CRIMINAL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AMERICAN JOURNAL OF COMPARATIVE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AMERICAN JOURNAL OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AMERICAN JOURNAL OF LAW & MEDICINE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AMERICAN LAW AND ECONOMICS REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ANNUAL REVIEW OF LAW AND SOCIAL SCIENCE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ANTITRUST LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ARAB LAW QUARTERLY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ARTIFICIAL INTELLIGENCE AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ASIA PACIFIC JOURNAL OF ENVIRONMENTAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ASIA PACIFIC LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ASIAN JOURNAL OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ASIAN JOURNAL OF LAW AND ECONOMICS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ASIAN JOURNAL OF LAW AND SOCIETY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ASIAN JOURNAL OF WTO & INTERNATIONAL HEALTH LAW AND POLICY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ATLANTIC LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AUSTRALIAN BUSINESS LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AUSTRALIAN FEMINIST LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AUSTRALIAN JOURNAL OF ADMINISTRATIVE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AUSTRALIAN JOURNAL OF COMPETITION AND CONSUMER LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('AUSTRALIAN LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('BANKING LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('BEHAVIORAL SCIENCES & THE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('BIOTECHNOLOGY LAW REPORT','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('BOSTON UNIVERSITY LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('BRICS LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('BUFFALO LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('BULLETIN OF MEDIEVAL CANON LAW-NEW SERIES','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CALIFORNIA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CAMBRIDGE INTERNATIONAL LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CAMBRIDGE LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CANADIAN JOURNAL OF LAW AND JURISPRUDENCE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CANADIAN JOURNAL OF LAW AND SOCIETY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CANADIAN JOURNAL OF WOMEN AND THE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CAPITAL MARKETS LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CATHOLIC UNIVERSITY LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CHINESE JOURNAL OF COMPARATIVE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CHINESE JOURNAL OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('COLUMBIA JOURNAL OF LAW AND SOCIAL PROBLEMS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('COLUMBIA JOURNAL OF TRANSNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('COLUMBIA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('COMMON MARKET LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('COMMUNICATION LAW AND POLICY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('COMPANY AND SECURITIES LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('COMPARATIVE AND INTERNATIONAL LAW JOURNAL OF SOUTHERN AFRICA-CILSA','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('COMPUTER LAW & SECURITY REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CONNECTICUT INSURANCE LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CORNELL INTERNATIONAL LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CORNELL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CRIME LAW AND SOCIAL CHANGE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CRIMINAL LAW AND PHILOSOPHY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CRIMINAL LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('CROATIAN YEARBOOK OF EUROPEAN LAW & POLICY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('DEAKIN LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('DENVER LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('DUKE LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ECCLESIASTICAL LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ECOLOGY LAW QUARTERLY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EDINBURGH LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EKONOMIA I PRAWO-ECONOMICS AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ELECTION LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ENVIRONMENTAL AND PLANNING LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN BUSINESS ORGANIZATION LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN COMPANY AND FINANCIAL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN COMPANY LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN CONSTITUTIONAL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN JOURNAL OF CRIME CRIMINAL LAW AND CRIMINAL JUSTICE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN JOURNAL OF HEALTH LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN JOURNAL OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN JOURNAL OF LAW AND ECONOMICS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN JOURNAL OF MIGRATION AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN PUBLIC LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('EUROPEAN REVIEW OF PRIVATE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('FAMILY LAW QUARTERLY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('FOOD AND DRUG LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('FORDHAM LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('FRONTIERS OF LAW IN CHINA','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('GAMING LAW REVIEW-ECONOMICS REGULATION COMPLIANCE AND POLICY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('GEORGE WASHINGTON LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('GEORGETOWN LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('GRIFFITH LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('HAGUE JOURNAL ON THE RULE OF LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('HARVARD CIVIL RIGHTS-CIVIL LIBERTIES LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('HARVARD ENVIRONMENTAL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('HARVARD INTERNATIONAL LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('HARVARD JOURNAL OF LAW AND PUBLIC POLICY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('HARVARD LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('HASTINGS LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('HEALTH ECONOMICS POLICY AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('HONG KONG LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('HUMAN RIGHTS LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ICL JOURNAL-VIENNA JOURNAL ON INTERNATIONAL CONSTITUTIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ICON-INTERNATIONAL JOURNAL OF CONSTITUTIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ICSID REVIEW-FOREIGN INVESTMENT LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('IDP-INTERNET LAW AND POLITICS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('IIC-INTERNATIONAL REVIEW OF INTELLECTUAL PROPERTY AND COMPETITION LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('IIUM LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INDIANA LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INDONESIA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INDUSTRIAL LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INFORMATION & COMMUNICATIONS TECHNOLOGY LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INSOLVENCY LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL & COMPARATIVE LAW QUARTERLY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL ASSOCIATION OF COOPERATIVA LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL COMMUNITY LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL CRIMINAL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL DATA PRIVACY LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL ENVIRONMENTAL AGREEMENTS-POLITICS LAW AND ECONOMICS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL FOR THE SEMIOTICS OF LAW-REVUE INTERNATIONALE DE SEMIOTIQUE JURIDIQUE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF COMPARATIVE LABOUR LAW AND INDUSTRIAL RELATIONS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF DISCRIMINATION AND THE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF LAW AND INFORMATION TECHNOLOGY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF LAW AND MANAGEMENT','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF LAW AND PSYCHIATRY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF LAW CRIME AND JUSTICE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF LAW IN CONTEXT','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF LAW POLICY AND THE FAMILY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF MARINE AND COASTAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF REFUGEE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL JOURNAL OF SPEECH LANGUAGE AND THE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL ORGANIZATIONS LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL REVIEW OF LAW AND ECONOMICS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('INTERNATIONAL SPORTS LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('IOWA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ISLAMIC LAW AND SOCIETY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ISRAEL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('ISSUES IN LAW & MEDICINE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL FOR EUROPEAN ENVIRONMENTAL & PLANNING LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF AFRICAN LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF ARTS MANAGEMENT LAW AND SOCIETY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF BANKING AND FINANCE LAW AND PRACTICE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF COMPETITION LAW & ECONOMICS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF CONFLICT & SECURITY LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF CORPORATE LAW STUDIES','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF CRIMINAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF CRIMINAL LAW & CRIMINOLOGY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF DIGITAL FORENSICS SECURITY AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF EAST ASIA AND INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF ENERGY & NATURAL RESOURCES LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF ENVIRONMENTAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF EUROPEAN COMPETITION LAW & PRACTICE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF HEALTH POLITICS POLICY AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF INTELLECTUAL PROPERTY LAW & PRACTICE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF INTERNATIONAL ECONOMIC LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF INTERNATIONAL TRADE LAW AND POLICY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW & ECONOMICS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW AND COURTSv','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW AND MEDICINE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW AND POLITICAL SCIENCES','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW AND RELIGION','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW AND SOCIAL DEVIANCE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW AND SOCIETY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW AND THE BIOSCIENCES','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW ECONOMICS & ORGANIZATION','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW FINANCE AND ACCOUNTING','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LAW MEDICINE & ETHICS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF LEGAL PLURALISM AND UNOFFICIAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF PENAL LAW AND CRIMINOLOGY-CEZA HUKUKU VE KRIMINOLOJI DERGISI','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF POLITICS AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF PRIVATE INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF PROPERTY PLANNING AND ENVIRONMENTAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF SOCIAL WELFARE AND FAMILY LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF THE AMERICAN ACADEMY OF PSYCHIATRY AND THE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF THE HISTORY OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JOURNAL OF WORLD ENERGY LAW & BUSINESS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('JURNAL CITA HUKUM-INDONESIAN LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('KOREAN JOURNAL OF INTERNATIONAL AND COMPARATIVE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW & LITERATURE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW & POLICY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW & PRACTICE OF INTERNATIONAL COURTS AND TRIBUNALS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW & SOCIETY REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW AND CRITIQUE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW AND DEVELOPMENT REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW AND FINANCIAL MARKETS REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW AND HISTORY REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW AND HUMAN BEHAVIOR','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW AND HUMANITIES','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW AND PHILOSOPHY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW AND SOCIAL INQUIRY-JOURNAL OF THE AMERICAN BAR FOUNDATION','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW CULTURE AND THE HUMANITIES','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW LIBRARY JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW PROBABILITY & RISK','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW TEACHER','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LAW TEXT CULTURE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LEIDEN JOURNAL OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LIVERPOOL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('LONDON REVIEW OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MACQUARIE LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MCGILL INTERNATIONAL JOURNAL OF SUSTAINABLE DEVELOPMENT LAW AND POLICY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MCGILL JOURNAL OF LAW AND HEALTH','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MEDICAL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MEDICINE AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MEDICINE LAW & SOCIETY','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MEDICINE SCIENCE AND THE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MELBOURNE JOURNAL OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MELBOURNE UNIVERSITY LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MEXICAN LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MICHIGAN LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MIDDLE EAST LAW AND GOVERNANCE','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MINNESOTA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MODERN LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('MONASH UNIVERSITY LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('NATIONAL TAIWAN UNIVERSITY LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('NETHERLANDS INTERNATIONAL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('NEW CRIMINAL LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('NEW YORK UNIVERSITY LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('NORTHWESTERN JOURNAL OF INTERNATIONAL LAW & BUSINESS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('NORTHWESTERN UNIVERSITY LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('NOTRE DAME LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('NTUT JOURNAL OF INTELLECTUAL PROPERTY LAW AND MANAGEMENT','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('OCEAN DEVELOPMENT AND INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('OSGOODE HALL LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('OXFORD JOURNAL OF LAW AND RELIGION','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('PERSON AND THE CHALLENGES-THE JOURNAL OF THEOLOGY EDUCATION CANON LAW AND SOCIAL STUDIES INSPIRED BY POPE JOHN PAUL II','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('POLISH YEARBOOK OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('PROCEEDINGS OF THE INSTITUTION OF CIVIL ENGINEERS-MANAGEMENT PROCUREMENT AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('PSYCHIATRY PSYCHOLOGY AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('PSYCHOLOGICAL INJURY & LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('PSYCHOLOGY AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('PSYCHOLOGY CRIME & LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('PSYCHOLOGY PUBLIC POLICY AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('PUBLIC LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('QUEENS LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('QUT LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('REVIEW OF CENTRAL AND EAST EUROPEAN LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('REVIEW OF EUROPEAN COMPARATIVE & INTERNATIONAL ENVIRONMENTAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('REVIEW OF LAW & ECONOMICS','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('REVISTA DE DIREITO DA CIDADE-CITY LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('REVISTA DE DIREITO SANITARIO-JOURNAL OF HEALTH LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('REVISTA DE EDUCACION Y DERECHO-EDUCATIONAL AND LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('REVISTA DE LLENGUA I DRET-JOURNAL OF LANGUAGE AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('REVUE CIRKEVNIHO PRAVA-CHURCH LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('RUSSIAN LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('RUTGERS UNIVERSITY LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('SECURITIES REGULATION LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('SOUTH AFRICAN JOURNAL OF BIOETHICS AND LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('SOUTHERN CALIFORNIA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('STANFORD JOURNAL OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('STANFORD LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('STATUTE LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('SYDNEY LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('TEXAS LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('TILBURG LAW REVIEW-JOURNAL OF INTERNATIONAL AND COMPARATIVE LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('TORT LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('TRANSNATIONAL ENVIRONMENTAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('TSINGHUA CHINA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UCLA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UNIFORM LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UNIVERSITY OF CHICAGO LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UNIVERSITY OF CINCINNATI LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UNIVERSITY OF ILLINOIS LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UNIVERSITY OF NEW SOUTH WALES LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UNIVERSITY OF PENNSYLVANIA JOURNAL OF INTERNATIONAL LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UNIVERSITY OF PENNSYLVANIA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UNIVERSITY OF PITTSBURGH LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UNIVERSITY OF TORONTO LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UNIVERSITY OF WESTERN AUSTRALIA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UTRECHT JOURNAL OF INTERNATIONAL AND EUROPEAN LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('UTRECHT LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('VANDERBILT LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('VESTNIK OF SAINT PETERSBURG UNIVERSITY-LAW-VESTNIK SANKT-PETERBURGSKOGO UNIVERSITETA-PRAVO','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('VESTNIK TOMSKOGO GOSUDARSTVENNOGO UNIVERSITETA-PRAVO-TOMSK STATE UNIVERSITY JOURNAL OF LAW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('VIRGINIA LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('WASHINGTON INTERNATIONAL LAW JOURNAL','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('WASHINGTON LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('WISCONSIN LAW REVIEW','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('YALE LAW JOURNAL','Publications') 


Select * from Scrl_CompetitionMasterTbl order by CompetitionId desc

--DBCC CHECKIDENT ('Scrl_CompetitionMasterTbl', RESEED, 250) 

--Delete from Scrl_CompetitionMasterTbl where CompetitionId=10100
