

Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Accounting Economics And Law-A Convivium','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Adelaide Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Administrative Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('African Journal Of International And Comparative Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Air & Space Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Alberta Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Alternative Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('American Bankruptcy Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('American Business Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('American Criminal Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('American Journal Of Comparative Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('American Journal Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('American Journal Of Law & Medicine','Publications')  
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Annual Review Of Law And Social Science','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Antitrust Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Arab Law Quarterly','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Artificial Intelligence And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Asia Pacific Journal Of Environmental Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Asia Pacific Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Asian Journal Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Asian Journal Of Law And Economics','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Asian Journal Of Law And Society','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Asian Journal Of Wto & International Health Law And Policy','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Atlantic Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Australian Business Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Australian Feminist Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Australian Journal Of Administrative Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Australian Journal Of Competition And Consumer Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Australian Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Banking Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Behavioral Sciences & The Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Biotechnology Law Report','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Boston University Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Brics Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Buffalo Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Bulletin Of Medieval Canon Law-New Series','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('California Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Cambridge International Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Cambridge Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Canadian Journal Of Law And Jurisprudence','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Canadian Journal Of Women And The Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Capital Markets Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Catholic University Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Chinese Journal Of Comparative Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Chinese Journal Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Columbia Journal Of Law And Social Problems','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Columbia Journal Of Transnational Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Columbia Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Common Market Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Communication Law And Policy','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Company And Securities Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Comparative And International Law Journal Of Southern Africa-Cilsa','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Computer Law & Security Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Connecticut Insurance Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Cornell International Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Cornell Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Crime Law And Social Change','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Criminal Law And Philosophy','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Criminal Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Croatian Yearbook Of European Law & Policy','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Deakin Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Denver Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Duke Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Ecclesiastical Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Ecology Law Quarterly','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Edinburgh Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Ekonomia I Prawo-Economics And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Election Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Environmental And Planning Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Business Organization Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Company And Financial Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Company Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Journal Of Crime Criminal Law And Criminal Justice','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Journal Of Health Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Journal Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Journal Of Law And Economics','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Journal Of Migration And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Public Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('European Review Of Private Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Family Law Quarterly','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Food And Drug Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Fordham Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Frontiers Of Law In China','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Gaming Law Review-Economics Regulation Compliance And Policy','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('George Washington Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Georgetown Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Griffith Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Harvard Environmental Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Harvard International Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Hastings Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Health Economics Policy And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Hong Kong Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Icl Journal-Vienna Journal On International Constitutional Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Icon-International Journal Of Constitutional Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Icsid Review-Foreign Investment Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Idp-Internet Law And Politics','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Iic-International Review Of Intellectual Property And Competition Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Iium Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Indiana Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Indonesia Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Industrial Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Information & Communications Technology Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Insolvency Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International & Comparative Law Quarterly','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Association Of Cooperativa Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Community Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Criminal Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Data Privacy Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Environmental Agreements-Politics Law And Economics','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal For The Semiotics Of Law-Revue Internationale De Semiotique Juridique','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal Of Comparative Labour Law And Industrial Relations','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal Of Discrimination And The Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal Of Law And Information Technology','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal Of Law And Management','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal Of Law And Psychiatry','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal Of Law Crime And Justice','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal Of Law In Context','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal Of Law Policy And The Family','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal Of Marine And Coastal Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Journal Of Speech Language And The Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Organizations Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Review Of Law And Economics','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('International Sports Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Iowa Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Islamic Law And Society','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Israel Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Issues In Law & Medicine','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal For European Environmental & Planning Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of African Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Arts Management Law And Society','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Banking And Finance Law And Practice','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Competition Law & Economics','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Conflict & Security Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Corporate Law Studies','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Criminal Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Criminal Law & Criminology','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Digital Forensics Security And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of East Asia And International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Energy & Natural Resources Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of European Competition Law & Practice','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Health Politics Policy And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Intellectual Property Law & Practice','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of International Economic Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of International Trade Law And Policy','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law & Economics','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law And Courts','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law And Medicine','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law And Political Sciences','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law And Religion','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law And Social Deviance','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law And Society','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law And The Biosciences','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law Economics & Organization','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law Finance And Accounting','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Law Medicine & Ethics','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Legal Pluralism And Unofficial Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Penal Law And Criminology-Ceza Hukuku Ve Kriminoloji Dergisi','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Politics And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Private International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Property Planning And Environmental Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of Social Welfare And Family Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of The American Academy Of Psychiatry And The Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of The History Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Journal Of World Energy Law & Business','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Jurnal Cita Hukum-Indonesian Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Korean Journal Of International And Comparative Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law & Literature','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law & Policy','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law & Practice Of International Courts And Tribunals','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law & Society Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law And Critique','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law And Development Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law And Financial Markets Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law And History Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law And Human Behavior','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law And Humanities','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law And Philosophy','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law And Social Inquiry-Journal Of The American Bar Foundation','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law Culture And The Humanities','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law Library Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law Probability & Risk','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law Teacher','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Law Text Culture','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Leiden Journal Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Liverpool Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('London Review Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Macquarie Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Mcgill International Journal Of Sustainable Development Law And Policy','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Mcgill Journal Of Law And Health','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Medicine And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Medicine Law & Society','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Medicine Science And The Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Melbourne Journal Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Melbourne University Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Mexican Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Michigan Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Middle East Law And Governance','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Minnesota Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Modern Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Monash University Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('National Taiwan University Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Netherlands International Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('New Criminal Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('New York University Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Northwestern Journal Of International Law & Business','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Northwestern University Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Notre Dame Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Ntut Journal Of Intellectual Property Law And Management','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Ocean Development And International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Osgoode Hall Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Oxford Journal Of Law And Religion','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Person And The Challenges-The Journal Of Theology Education Canon Law And Social Studies Inspired By Pope John Paul Ii','Publications')
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Polish Yearbook Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Proceedings Of The Institution Of Civil Engineers-Management Procurement And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Psychiatry Psychology And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Psychological Injury & Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Psychology And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Psychology Crime & Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Psychology Public Policy And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Public Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Queens Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Qut Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Review Of Central And East European Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Review Of European Comparative & International Environmental Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Review Of Law & Economics','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Revista De Direito Da Cidade-City Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Revista De Direito Sanitario-Journal Of Health Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Revista De Educacion Y Derecho-Educational And Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Revista De Llengua I Dret-Journal Of Language And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Revue Cirkevniho Prava-Church Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Russian Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Rutgers University Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Securities Regulation Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('South African Journal Of Bioethics And Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Southern California Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Stanford Journal Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Stanford Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Statute Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Sydney Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Texas Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Tilburg Law Review-Journal Of International And Comparative Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Tort Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Transnational Environmental Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Tsinghua China Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Ucla Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Uniform Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('University Of Chicago Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('University Of Cincinnati Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('University Of Illinois Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('University Of New South Wales Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('University Of Pennsylvania Journal Of International Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('University Of Pennsylvania Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('University Of Pittsburgh Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('University Of Toronto Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('University Of Western Australia Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Utrecht Journal Of International And European Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Utrecht Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Vanderbilt Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Vestnik Of Saint Petersburg University-Law-Vestnik Sankt-Peterburgskogo Universiteta-Pravo','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Vestnik Tomskogo Gosudarstvennogo Universiteta-Pravo-Tomsk State University Journal Of Law','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Virginia Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Washington International Law Journal','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Washington Law Review','Publications') 
Insert into Scrl_CompetitionMasterTbl (CompName,Competitiontype) values ('Wisconsin Law Review','Publications') 

--Select * from Scrl_CompetitionMasterTbl order by CompetitionId desc
--DBCC CHECKIDENT ('Scrl_CompetitionMasterTbl', RESEED, 250) 

Select * from Scrl_CompetitionMasterTbl where CompetitionId>250 order by CompetitionId desc
